services:
  plicko:
    build: .
    container_name: plicko
    restart: unless-stopped
    networks:
      - proxy
      - plicko
    env_file:
      - .env
    volumes:
      - artifacts:/artifacts
  postgres:
    image: postgres
    restart: unless-stopped
    env_file:
      - path: .env
        required: false
      - path: ../stack.env
        required: false
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=plicko
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - plicko

networks:
  proxy:
    external: true
  plicko:

volumes:
  artifacts:
  postgres_data:
