services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
  postgres:
    image: postgres
    restart: no
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=plicko
